language: node_js
node_js: iojs

git:
  submodules: false

matrix:
  include:
    - script:
      - sudo apt-get update
      - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
      - npm i canvas
      - npm test
      env: TEST_SUITE=node-canvas
      node_js: iojs-v2.5.0 # TODO update when canvas package works with latest io.js
    - script: "npm run pretest && npm run test-browser"
      env: TEST_SUITE=browser
      addons:
        sauce_connect:
          username: "jsdom"
          access_key: "7d402b1d-0388-467c-8d99-edf195456eee"

script: "npm run lint && npm test"
